service: nextjs-serverless

plugins:
  - serverless-offline
  - serverless-plugin-warmup
  - serverless-dotenv-plugin

custom:
  serverless-offline:
    port: 8000
  dotenv:
    path: .env

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-1
  memorySize:
    prod: 1024
    default: 512
  timeout: 15
  # environment:
  #   NODE_ENV: ${env:NODE_ENV}
  #   IN_LAMBDA: ${env:IN_LAMBDA}
  #   region: ${env:region}
  #   identityPoolId: ${env:identityPoolId}
  #   identityPoolRegion: ${env:identityPoolRegion}
  #   userPoolId: ${env:userPoolId}
  #   userPoolWebClientId: ${env:userPoolWebClientId}

functions:
  next:
    handler: lambda.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{any+}
          method: ANY
    warmup: true

resources:
  Description: Next.js testing in AWS lambda